#!/bin/bash          
echo Pushing to production at athina.med.duth.gr
cd dist
git init
git remote add production dokku@athina.med.duth.gr:carre-educational-aggregator
git add .
git commit -am"deploy new version"
git push -f production master
cd ..