#!/bin/bash          
cd dist
git init
git remote add production dokku@athina.med.duth.gr:carre-educational-aggregator
git remote add docker git@github.com:carre-project/carre-edu-docker.git
git add .
git commit -am"deploy new version"
git push -f production master
git push -f docker master
cd ..