#!/bin/bash    

# stop executing if any command exits with non zero value
set -e

echo "Fetching changes from repo..."
git pull;


PS3='Create new tag for this version? (y/N): '
options=("y" "n")
select opt in "${options[@]}"
do
    case $opt in
        "y")
            export TASK=":bump"
            break
            ;;
        "n")
            export TASK=":bump-only"
            break
            ;;
        *) echo "Invalid option"; break ;;
    esac
done

PS3='Change version (Semantic Versioning): '
options=("Major 1.x.x" "Minor x.1.x" "Patch x.x.1" "No change")
select opt in "${options[@]}"
do
    case $opt in
        "Major 1.x.x")
            grunt bump:major$TASK
            break
            ;;
        "Minor x.1.x")
            grunt bump:minor$TASK
            break
            ;;
        "Patch x.x.1")
            grunt bump:patch$TASK
            break
            ;;
        "No change")
            break
            ;;
        *) echo "Invalid option"; break ;;
    esac
done


echo "Uploading to repository..."
git add --all release-notes/
grunt changelog:v1 && grunt changelog:v1

sleep 1 && git add --all release-notes/ 
echo -ne "\e[92mAdd to Changelog?\e[39m : "
read -e MSG

git commit -am"CLI: $MSG";
git push
# && git push --tags