exports.riskelements=function(){
	var data =[
	'acute kidney injury',
	'chronic kidney disease',
	'death',
	'ischemic heart disease',
	'peripheral arterial disease',
	'atrial fibrillation',
	'stroke',
	'ischemic heart disease',
	'cardiovascular disease',
	'heart failure',
	'hypertension',
	'hypotension',
	'anemia',
	'acute myocardial infarction',
	'peripheral vascular disease',
	'hyperkalemia',
	'chronic obstructive pulmonary disease',
	'depression',
	'diabetes',
	'diabetic nephropathy',
	'ischemic stroke',
	'coronary angiography',
	'diuretics',
	'renin-angiotensin system',
	'statins',
	'dyslipidemia',
	'cancer',
	'systolic blood pressure',
	'left ventricular hypertrophy',
	'obesity',
	'cholesterol serum concentration',
	'hdl',
	'triclycerides serum concentration',
	'asthma',
	'atrial fibrillation',
	'colorectal cancer',
	'gastric cardiac cancer',
	'pancreatic cancer',
	'cholelithiasis',
	'osteoarthritis',
	'obstructive sleep apnoea',
	'albuminuria',
	'hyperuricemia'
	];
	return data;
};